no-tests = true
no-hooks = true
no-driver-templates = true

[psql]
  host      = "localhost"
  port      = 5432
  sslmode   = "disable"
  dbname    = "golang-layout"
  user      = "postgres"
  pass      = "postgres"
  schema    = "public"
  blacklist = ["goose_db_version", "schema_migrations"]
