// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.api.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadAllRequest struct {
	Limit                int64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{2}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadAllRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadAllRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadAllResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{3}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReadRequest struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{5}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *User                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReplaceRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceRequest) Reset()         { *m = ReplaceRequest{} }
func (m *ReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceRequest) ProtoMessage()    {}
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{7}
}

func (m *ReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceRequest.Unmarshal(m, b)
}
func (m *ReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceRequest.Merge(m, src)
}
func (m *ReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceRequest.Size(m)
}
func (m *ReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceRequest proto.InternalMessageInfo

func (m *ReplaceRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReplaceRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8321725bb568719, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "github.reviz0r.httpapi.profile.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "github.reviz0r.httpapi.profile.CreateResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "github.reviz0r.httpapi.profile.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "github.reviz0r.httpapi.profile.ReadAllResponse")
	proto.RegisterType((*ReadRequest)(nil), "github.reviz0r.httpapi.profile.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "github.reviz0r.httpapi.profile.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "github.reviz0r.httpapi.profile.UpdateRequest")
	proto.RegisterType((*ReplaceRequest)(nil), "github.reviz0r.httpapi.profile.ReplaceRequest")
	proto.RegisterType((*DeleteRequest)(nil), "github.reviz0r.httpapi.profile.DeleteRequest")
}

func init() { proto.RegisterFile("profile.api.proto", fileDescriptor_c8321725bb568719) }

var fileDescriptor_c8321725bb568719 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x95, 0x6e, 0x0b, 0xc2, 0x65, 0x1d, 0x35, 0xd3, 0x54, 0x65, 0xbc, 0x44, 0x11, 0x12,
	0x1b, 0x5b, 0x13, 0xd6, 0x5d, 0x60, 0xb7, 0xf2, 0xce, 0x61, 0x07, 0x8a, 0x76, 0xd9, 0x05, 0xb9,
	0xcd, 0xd3, 0xcc, 0x5a, 0x1a, 0x9b, 0xd8, 0xdd, 0x34, 0xd0, 0x2e, 0x48, 0x5c, 0x90, 0xb8, 0x14,
	0xc4, 0x8d, 0x4f, 0xc5, 0x57, 0xe0, 0x0b, 0xf0, 0x0d, 0x90, 0x5f, 0x3a, 0xda, 0xb2, 0xd2, 0x30,
	0x71, 0xaa, 0x6c, 0xff, 0xfd, 0xfc, 0x7f, 0x7e, 0x5e, 0x1a, 0x54, 0xe5, 0x39, 0xeb, 0xd2, 0x14,
	0x42, 0xc2, 0x69, 0xc8, 0x73, 0x26, 0x19, 0xbe, 0x99, 0x50, 0x79, 0xd0, 0x6f, 0x87, 0x39, 0x1c,
	0xd1, 0xb7, 0xf7, 0xf2, 0xf0, 0x40, 0x4a, 0x6e, 0x4f, 0x95, 0xd2, 0x5b, 0x4d, 0x18, 0x4b, 0x52,
	0x88, 0xb4, 0xba, 0xdd, 0xef, 0x46, 0xd0, 0xe3, 0xf2, 0xc4, 0x5c, 0xf6, 0xfc, 0xc9, 0xc3, 0x2e,
	0x85, 0x34, 0x7e, 0xdd, 0x23, 0xe2, 0xd0, 0x2a, 0xae, 0x5b, 0x05, 0xe1, 0x34, 0x22, 0x59, 0xc6,
	0x24, 0x91, 0x94, 0x65, 0xc2, 0x9e, 0x6e, 0xea, 0x9f, 0x4e, 0x3d, 0x81, 0xac, 0x2e, 0x8e, 0x49,
	0x92, 0x40, 0x1e, 0x31, 0xae, 0x15, 0xe7, 0xa8, 0xcb, 0x3d, 0x16, 0x43, 0x6a, 0x16, 0xc1, 0x0b,
	0xb4, 0xf8, 0x28, 0x07, 0x22, 0xa1, 0x05, 0x6f, 0xfa, 0x20, 0x24, 0xbe, 0x8f, 0xe6, 0xfb, 0x02,
	0xf2, 0x9a, 0xe3, 0x3b, 0x6b, 0xe5, 0xc6, 0xed, 0xf0, 0xef, 0xef, 0x0a, 0xf7, 0x04, 0xe4, 0x2d,
	0x7d, 0x23, 0xf0, 0x51, 0x65, 0x18, 0x4a, 0x70, 0x96, 0x09, 0xc0, 0x15, 0x54, 0xa2, 0xb1, 0x8e,
	0x34, 0xd7, 0x2a, 0xd1, 0x38, 0xc8, 0x51, 0xa5, 0x05, 0x24, 0x6e, 0xa6, 0xe9, 0xd0, 0x6d, 0x19,
	0x2d, 0xa4, 0xb4, 0x47, 0xa5, 0x15, 0x99, 0x05, 0x5e, 0x41, 0x2e, 0xeb, 0x76, 0x05, 0xc8, 0x5a,
	0x49, 0x6f, 0xdb, 0x15, 0x6e, 0x20, 0x57, 0x67, 0x46, 0xd4, 0xe6, 0x34, 0x9d, 0x17, 0x9a, 0xb4,
	0x84, 0xc3, 0xc4, 0x85, 0x4f, 0xd5, 0xf1, 0x2e, 0x11, 0x87, 0x2d, 0xab, 0x0c, 0x76, 0xd1, 0xd2,
	0x99, 0xa7, 0xc5, 0xda, 0x41, 0x0b, 0x0a, 0x58, 0xd4, 0x1c, 0x7f, 0xae, 0xf0, 0x1b, 0xcd, 0x95,
	0xe0, 0x25, 0x2a, 0xab, 0x70, 0x43, 0xfe, 0x89, 0x17, 0x8e, 0x10, 0x96, 0x0a, 0x13, 0x3e, 0x47,
	0x57, 0x4c, 0x48, 0x8b, 0x77, 0xf1, 0x0a, 0x7c, 0x72, 0xd0, 0xe2, 0x1e, 0x8f, 0x47, 0xaa, 0x39,
	0xc9, 0x37, 0x8c, 0x5d, 0xfa, 0xd7, 0xd8, 0x17, 0xca, 0xfd, 0xbe, 0xaa, 0x37, 0x4f, 0x49, 0xe7,
	0xff, 0xf3, 0x04, 0xb7, 0xd0, 0xe2, 0x63, 0x48, 0x61, 0xea, 0x53, 0x1b, 0x3f, 0x5d, 0x54, 0x56,
	0xfa, 0x57, 0x90, 0x1f, 0xd1, 0x0e, 0xe0, 0x2f, 0x0e, 0x72, 0x4d, 0x7f, 0xe2, 0xfa, 0x2c, 0x9f,
	0xb1, 0x91, 0xf0, 0xc2, 0xa2, 0x72, 0x53, 0xc0, 0x60, 0x63, 0xd0, 0xac, 0xe2, 0x25, 0xb3, 0xe9,
	0x67, 0x70, 0xec, 0x2b, 0xe0, 0xf7, 0xdf, 0x7f, 0x7c, 0x2e, 0x55, 0x83, 0xcb, 0xd1, 0xd1, 0x56,
	0xa4, 0x5b, 0x69, 0xc7, 0xe4, 0xf5, 0x9b, 0x83, 0x2e, 0xd9, 0x06, 0xc5, 0x33, 0x8d, 0xc6, 0xa7,
	0xc7, 0x8b, 0x0a, 0xeb, 0x2d, 0xd9, 0xd6, 0xa0, 0x79, 0x03, 0xaf, 0x3e, 0x03, 0xe9, 0x93, 0x34,
	0xd5, 0x58, 0xc2, 0x5f, 0x3b, 0xa6, 0xf2, 0xc0, 0xe7, 0x24, 0xa1, 0x59, 0xb2, 0xae, 0x29, 0xcb,
	0xf8, 0x37, 0x25, 0xfe, 0xea, 0xa0, 0x79, 0x15, 0x06, 0x6f, 0x14, 0x31, 0x1b, 0x92, 0x6d, 0x16,
	0x13, 0x5b, 0xac, 0xed, 0x41, 0x73, 0x19, 0x63, 0x85, 0xc5, 0x32, 0xd0, 0x58, 0x7e, 0xfb, 0xc4,
	0xa7, 0xb1, 0xa6, 0x59, 0xc1, 0x95, 0x33, 0x9a, 0xe8, 0x1d, 0x8d, 0x4f, 0xdb, 0x26, 0x71, 0x1f,
	0x1d, 0xe4, 0x9a, 0x66, 0x9f, 0x5d, 0xcf, 0xb1, 0xa1, 0xf0, 0x56, 0xfe, 0x68, 0xdd, 0x27, 0xea,
	0xcf, 0x38, 0x78, 0x30, 0x68, 0x7a, 0xb8, 0x66, 0xb4, 0x86, 0xc2, 0xf4, 0xf1, 0x28, 0x8c, 0x37,
	0x01, 0x63, 0xab, 0xf8, 0x41, 0x57, 0x51, 0xb7, 0x7a, 0x91, 0x2a, 0x8e, 0xce, 0xc4, 0x54, 0x9c,
	0xc6, 0xa0, 0x79, 0x0d, 0x57, 0x47, 0x71, 0x46, 0x38, 0x1a, 0xe7, 0x73, 0x9c, 0x22, 0xd7, 0x4c,
	0xc5, 0xec, 0x9c, 0x8c, 0x4d, 0xcf, 0x54, 0x88, 0x4d, 0x0d, 0x61, 0xb4, 0x93, 0x10, 0x57, 0xef,
	0x4e, 0x40, 0x3c, 0x5c, 0xdf, 0xbf, 0x63, 0x5d, 0x3b, 0xac, 0x17, 0x59, 0xe7, 0x48, 0x39, 0xd7,
	0xd5, 0x97, 0x8b, 0x1f, 0x26, 0x91, 0xb5, 0x6f, 0xbb, 0xda, 0x68, 0xfb, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0xac, 0xe2, 0xcd, 0x4c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Replace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/Replace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/github.reviz0r.httpapi.profile.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*empty.Empty, error)
	Replace(context.Context, *ReplaceRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) ReadAll(ctx context.Context, req *ReadAllRequest) (*ReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}
func (*UnimplementedUserServiceServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UpdateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Replace(ctx context.Context, req *ReplaceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replace not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/Replace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Replace(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.reviz0r.httpapi.profile.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.reviz0r.httpapi.profile.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _UserService_ReadAll_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UserService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _UserService_Replace_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.api.proto",
}
